### ISSUE TITLE
Robot randomly just drives off the field when scoring

### ISSUE THREAD

**Issue by mvog2501** [SouthwestRoboticsProgramming/2023_Main_Robot#102]
**Describe the bug**
The robot drove off the field when pressing the top left button to score on the virtual button panel. The robot was rotated roughly 180 degrees off from the correct scoring location and upon click, the robot drove off the upper right hand side of the simulator. Other buttons had been pressed in the session and everything was working.

**To Reproduce**
I dunno.

**Additional context**
Pathfinder, Shufflelog, and Messenger were all running

**Comment by rmheuer** [comment]
I encountered this issue earlier, it appears to be an issue with the simulated gyro. I don't know if it happens on the actual robot

**Comment by mvog2501** [comment]
Issue was caused by staring pathfinding while still in an object, I belive that the backup path was really stale and the robot was not where that path was initially calculated. Could have also been caused by simulated gyro which has been flakey at best.

**Comment by mvog2501** [comment]
It is just a gyro issue, the path still works if the robot is not rotated at all.
