### ISSUE TITLE
Arm damping

### ISSUE THREAD

**Issue by mvog2501** [SouthwestRoboticsProgramming/2023_Main_Robot#125]
While swapping the arm to use full motor power was a good thing, it does bring up the need for some sort of arm damping. Currently, when it navigates up to a position, it rocks the whole robot with it. The solution could be as simple as adding a kD constant or as complex as limiting acceleration.

**Comment by rmheuer** [comment]
kD is available for tuning in NetworkTables so that can be tested tomorrow

**Comment by rmheuer** [comment]
Arm movement was good at hcpa
