### ISSUE TITLE
Arm shakey shakey

### ISSUE THREAD

**Issue by mvog2501** [SouthwestRoboticsProgramming/2023_Main_Robot#126]
It would seem that the arm still has a bug of shaking around when it is manually nudged so that the upper segment is parallel to the floor and perpendicular to the bottom segment. Dunno if arm pathfinding was enabled when this issue occurred. More testing is needed.

**Comment by rmheuer** [comment]
Arm pathfinding was definitely not enabled because it is commented

**Comment by rmheuer** [comment]
Does not appear to happen in the simulator

**Comment by rmheuer** [comment]
Seems to be relatively fine on the robot currently
