### ISSUE TITLE
Substation Assists

### ISSUE THREAD

**Issue by mvog2501** [SouthwestRoboticsProgramming/2023_Main_Robot#145]
The addition of limelight-aided substation pickup is a massive help to driving. This could be improved by forcing robot's relative mode when the snap key is held for the substation. When testing today, I just snapped to angle, went robot relative, and drove forward.

Another change work checking out is assisting the driver in driving straight by automatically rounding inputs that are in the forward direction to absolute forward. This could help with confused drivers but it may also remove the ability to smoothly adjust. Something to check out for sure tho.

**Comment by mvog2501** [comment]
This is being worked on on [this branch](https://github.com/SouthwestRoboticsProgramming/2023_Main_Robot/tree/minor_controls_changes)

**Comment by rmheuer** [comment]
minor-control-fixes was merged
