### ISSUE TITLE
Update Robot NetworkTables library to 2023 NT4

### ISSUE THREAD

**Issue by rmheuer** [SouthwestRoboticsProgramming/2023_Main_Robot#67]
The `NT***` classes should use the new NT4 API in 2023 WPILib instead of the old `NetworkTableEntry`.

**Comment by foehammer127** [comment]
Is this being hacked on?

**Comment by rmheuer** [comment]
Not currently, this isn't required to be done since the NT3 API still works properly.

**Comment by mvog2501** [comment]
@rmheuer Done?

**Comment by rmheuer** [comment]
Yes
